<a href="https://colab.research.google.com/github/Kzis/ml-project/blob/master/k_mean1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
from copy import deepcopy
import numpy as np
import pandas as pd

from sklearn.datasets import load_wine

# load dataset
data = load_wine()

# feature matrix
X = data.data

# target vector
y = data.target

# class labels
labels = data.feature_names

wine = pd.DataFrame(X, columns=labels) #convert numpy for show
wine.head()


alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

In [59]:
wine.describe().transpose()

count        mean  ...       75%      max
alcohol                       178.0   13.000618  ...   13.6775    14.83
malic_acid                    178.0    2.336348  ...    3.0825     5.80
ash                           178.0    2.366517  ...    2.5575     3.23
alcalinity_of_ash             178.0   19.494944  ...   21.5000    30.00
magnesium                     178.0   99.741573  ...  107.0000   162.00
total_phenols                 178.0    2.295112  ...    2.8000     3.88
flavanoids                    178.0    2.029270  ...    2.8750     5.08
nonflavanoid_phenols          178.0    0.361854  ...    0.4375     0.66
proanthocyanins               178.0    1.590899  ...    1.9500     3.58
color_intensity               178.0    5.058090  ...    6.2000    13.00
hue                           178.0    0.957449  ...    1.1200     1.71
od280/od315_of_diluted_wines  178.0    2.611685  ...    3.1700     4.00
proline                       178.0  746.893258  ...  985.0000  1680.00

[13 rows x 8 columns]

In [60]:
wine.shape

(178, 13)

In [69]:
##### Data Preprocessing #####

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit only to the training data
scaler.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [70]:
##### Training the model #####
from sklearn.cluster import KMeans

model = KMeans(n_clusters=3, init = 'random', max_iter = 100, random_state = 5)
kmeans = model.fit(X)
kmeans


KMeans(algorithm='auto', copy_x=True, init='random', max_iter=100, n_clusters=3,
       n_init=10, n_jobs=None, precompute_distances='auto', random_state=5,
       tol=0.0001, verbose=0)

In [111]:
# Getting the cluster labels
output = kmeans.predict(X)
print(type(output))
print(output)

<class 'numpy.ndarray'>
[2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 2 2 0 0 2 2 0 2 2 2 2 2 2 0 0
 2 2 0 0 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 0 1 0 1 1 0 1 1 0 0 0 1 1 2
 0 1 1 1 0 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 1 1 1 0 0 1 1 0 0 1 0
 0 1 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1]


In [76]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [77]:
wine['label'] = y
wine.head()

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  label
0    14.23        1.71  2.43  ...                          3.92   1065.0      0
1    13.20        1.78  2.14  ...                          3.40   1050.0      0
2    13.16        2.36  2.67  ...                          3.17   1185.0      0
3    14.37        1.95  2.50  ...                          3.45   1480.0      0
4    13.24        2.59  2.87  ...                          2.93    735.0      0

[5 rows x 14 columns]

In [82]:
avg = wine.groupby('label').mean()
avg

alcohol  malic_acid  ...  od280/od315_of_diluted_wines      proline
label                         ...                                           
0      13.744746    2.010678  ...                      3.157797  1115.711864
1      12.278732    1.932676  ...                      2.785352   519.507042
2      13.153750    3.333750  ...                      1.683542   629.895833

[3 rows x 13 columns]

In [83]:
op_df=pd.DataFrame(X)
op_df['label'] = output
op_df.head()

0     1     2     3      4     5  ...     8     9    10    11      12  label
0  14.23  1.71  2.43  15.6  127.0  2.80  ...  2.29  5.64  1.04  3.92  1065.0      2
1  13.20  1.78  2.14  11.2  100.0  2.65  ...  1.28  4.38  1.05  3.40  1050.0      2
2  13.16  2.36  2.67  18.6  101.0  2.80  ...  2.81  5.68  1.03  3.17  1185.0      2
3  14.37  1.95  2.50  16.8  113.0  3.85  ...  2.18  7.80  0.86  3.45  1480.0      2
4  13.24  2.59  2.87  21.0  118.0  2.80  ...  1.82  4.32  1.04  2.93   735.0      0

[5 rows x 14 columns]

In [84]:
avg_op = op_df.groupby('label').mean()
avg_op

0         1         2   ...        10        11           12
label                                 ...                                 
0      12.929839  2.504032  2.408065  ...  0.883968  2.365484   728.338710
1      12.516667  2.494203  2.288551  ...  0.941159  2.490725   458.231884
2      13.804468  1.883404  2.426170  ...  1.078298  3.114043  1195.148936

[3 rows x 13 columns]

In [105]:
from sklearn.metrics.pairwise import euclidean_distances
vector_master0 = avg.to_numpy()[0]
vector_master1 = avg.to_numpy()[1]
vector_master2 = avg.to_numpy()[2]

vector_predict0 = avg_op.to_numpy()[0]
vector_predict1 = avg_op.to_numpy()[1]
vector_predict2 = avg_op.to_numpy()[2]

vector00 = np.round( np.sum( np.sqrt((vector_master0-vector_predict0)**2)) )
vector01 = np.round( np.sum( np.sqrt((vector_master0-vector_predict1)**2)) )
vector02 = np.round( np.sum( np.sqrt((vector_master0-vector_predict2)**2)) )
print("--------")
print("0-0,",vector00)
print("0-1,",vector01)
print("0-2,",vector02)

vector10 = np.round( np.sum( np.sqrt((vector_master1-vector_predict0)**2)) )
vector11 = np.round( np.sum( np.sqrt((vector_master1-vector_predict1)**2)) )
vector12 = np.round( np.sum( np.sqrt((vector_master1-vector_predict2)**2)) )
print("--------")
print("1-0,",vector10)
print("1-1,",vector11)
print("1-2,",vector12)

vector20 = np.round( np.sum( np.sqrt((vector_master2-vector_predict0)**2)) )
vector21 = np.round( np.sum( np.sqrt((vector_master2-vector_predict1)**2)) )
vector22 = np.round( np.sum( np.sqrt((vector_master2-vector_predict2)**2)) )
print("--------")
print("2-0,",vector20)
print("2-1,",vector21)
print("2-2,",vector22)

--------
0-0, 398.0
0-1, 682.0
0-2, 81.0
--------
1-0, 224.0
1-1, 67.0
1-2, 696.0
--------
2-0, 110.0
2-1, 187.0
2-2, 586.0


In [112]:
print(output)
print("----")
output[output == 2] = 99
output[output == 0] = 2
output[output == 99] = 0
print(output)

[2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 2 2 0 0 2 2 0 2 2 2 2 2 2 0 0
 2 2 0 0 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 0 1 0 1 1 0 1 1 0 0 0 1 1 2
 0 1 1 1 0 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 1 1 1 0 0 1 1 0 0 1 0
 0 1 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1]
----
[0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 0 0 2 2 0 0 2 0 0 0 0 0 0 2 2
 0 0 2 2 0 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 1 2 1 1 2 1 1 2 2 2 1 1 0
 2 1 1 1 2 1 1 2 2 1 1 1 1 1 2 2 1 1 1 1 1 2 2 1 2 1 2 1 1 1 2 1 1 1 1 2 1
 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1 2 2 2 2 1 1 1 2 2 1 1 2 2 1 2
 2 1 1 1 1 2 2 2 1 2 2 2 1 2 1 2 2 1 2 2 2 2 1 1 2 2 2 2 2 1]


In [113]:
from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y,output))

[[46  0 13]
 [ 1 50 20]
 [ 0 19 29]]


In [114]:
print(classification_report(y,output))

              precision    recall  f1-score   support

           0       0.98      0.78      0.87        59
           1       0.72      0.70      0.71        71
           2       0.47      0.60      0.53        48

    accuracy                           0.70       178
   macro avg       0.72      0.70      0.70       178
weighted avg       0.74      0.70      0.71       178

