<a href="https://colab.research.google.com/github/Kzis/ml-project/blob/master/k_mean1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from copy import deepcopy
import numpy as np
import pandas as pd

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

from matplotlib import pyplot as plt
plt.rcParams['figure.figsize'] = (16, 9)
plt.style.use('ggplot')

# load dataset
data = load_wine()
X = data.data #attribute class
y = data.target #label class

wine = pd.DataFrame(X, columns=data.feature_names) #convert numpy for show
wine.head()


alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

In [10]:
wine.describe().transpose()

count        mean  ...       75%      max
alcohol                       178.0   13.000618  ...   13.6775    14.83
malic_acid                    178.0    2.336348  ...    3.0825     5.80
ash                           178.0    2.366517  ...    2.5575     3.23
alcalinity_of_ash             178.0   19.494944  ...   21.5000    30.00
magnesium                     178.0   99.741573  ...  107.0000   162.00
total_phenols                 178.0    2.295112  ...    2.8000     3.88
flavanoids                    178.0    2.029270  ...    2.8750     5.08
nonflavanoid_phenols          178.0    0.361854  ...    0.4375     0.66
proanthocyanins               178.0    1.590899  ...    1.9500     3.58
color_intensity               178.0    5.058090  ...    6.2000    13.00
hue                           178.0    0.957449  ...    1.1200     1.71
od280/od315_of_diluted_wines  178.0    2.611685  ...    3.1700     4.00
proline                       178.0  746.893258  ...  985.0000  1680.00

[13 rows x 8 columns]

In [11]:
wine.shape

(178, 13)

In [0]:
# feature matrix
X = data.data

# target vector
y = data.target

# class labels
labels = data.feature_names

In [0]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [14]:
##### Data Preprocessing #####

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit only to the training data
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [0]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
##### Training the model #####
from sklearn.cluster import KMeans

model = KMeans(n_clusters=3, init = 'random', max_iter = 100, random_state = 5)
kmeans = model.fit(X_train,X_test)
kmeans


KMeans(algorithm='auto', copy_x=True, init='random', max_iter=100, n_clusters=3,
       n_init=10, n_jobs=None, precompute_distances='auto', random_state=5,
       tol=0.0001, verbose=0)

In [21]:
##### Predictions and Evaluation #####

predictions = model.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test,predictions))

[[ 0  0 13]
 [16  0  0]
 [ 0 16  0]]


In [22]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      13.0
           1       0.00      0.00      0.00      16.0
           2       0.00      0.00      0.00      16.0

    accuracy                           0.00      45.0
   macro avg       0.00      0.00      0.00      45.0
weighted avg       0.00      0.00      0.00      45.0

